#!/bin/busybox sh
set -eu

busybox=/bin/busybox

"$busybox" mount -t devtmpfs devtmpfs /dev
"$busybox" mount -t proc proc /proc
"$busybox" mount -t sysfs sysfs /sys

export TERM=dumb

printf 'Welcome to the PanamaKVM interactive guest.\n'
printf 'Type exit to stop the virtual machine.\n'
printf 'Ready. [PANAMAKVM_INTERACTIVE_READY]\n\n'

if "$busybox" setsid -c "$busybox" cttyhack "$busybox" sh -c \
    'stty isig intr "^C"; exec /bin/busybox sh -i' \
    </dev/console >/dev/console 2>&1; then
    shell_status=0
else
    shell_status=$?
fi

printf '\nShell exited with status %s. Stopping VM...\n' "$shell_status"
"$busybox" sync
exec "$busybox" reboot -f
