package io.sagittarius.panamakvm.cli.terminal;

import java.util.Objects;
import java.util.function.IntConsumer;

/**
 * Removes cursor-position reports generated by a host terminal from serial
 * input while preserving ordinary bytes and terminal key sequences.
 */
final class TerminalControlResponseFilter {
    private static final int MAX_INPUT_BYTE = 0xff;
    private static final char ESCAPE = 0x1b;
    private static final char CONTROL_SEQUENCE_INTRODUCER = '[';
    private static final char COORDINATE_SEPARATOR = ';';
    private static final char CURSOR_POSITION_REPORT_END = 'R';
    private static final int CONTROL_SEQUENCE_PREFIX_LENGTH = 2;

    private final IntConsumer receiver;
    private final StringBuilder pending = new StringBuilder();

    TerminalControlResponseFilter(IntConsumer receiver) {
        this.receiver = Objects.requireNonNull(receiver, "receiver");
    }

    void accept(int value) {
        if (value < 0 || value > MAX_INPUT_BYTE) {
            throw new IllegalArgumentException("Terminal input must be an unsigned byte: " + value);
        }
        if (pending.isEmpty()) {
            if (value == ESCAPE) {
                pending.append((char) value);
            } else {
                receiver.accept(value);
            }
            return;
        }

        pending.append((char) value);
        if (pending.length() == CONTROL_SEQUENCE_PREFIX_LENGTH && value != CONTROL_SEQUENCE_INTRODUCER) {
            flushPending();
        } else if (pending.length() > CONTROL_SEQUENCE_PREFIX_LENGTH) {
            if (isCursorPositionReport()) {
                pending.setLength(0);
            } else if (!canBecomeCursorPositionReport()) {
                flushPending();
            }
        }
    }

    void finish() {
        flushPending();
    }

    private boolean isCursorPositionReport() {
        if (pending.charAt(pending.length() - 1) != CURSOR_POSITION_REPORT_END) {
            return false;
        }
        int separator = pending.indexOf(String.valueOf(COORDINATE_SEPARATOR));
        if (separator <= CONTROL_SEQUENCE_PREFIX_LENGTH
                || separator + 1 >= pending.length() - 1) {
            return false;
        }
        return containsOnlyDigits(CONTROL_SEQUENCE_PREFIX_LENGTH, separator)
                && containsOnlyDigits(separator + 1, pending.length() - 1);
    }

    private boolean canBecomeCursorPositionReport() {
        for (int index = CONTROL_SEQUENCE_PREFIX_LENGTH; index < pending.length(); index++) {
            char value = pending.charAt(index);
            if (!isDigit(value) && value != COORDINATE_SEPARATOR) {
                return false;
            }
        }
        return true;
    }

    private boolean containsOnlyDigits(int start, int end) {
        for (int index = start; index < end; index++) {
            if (!isDigit(pending.charAt(index))) {
                return false;
            }
        }
        return true;
    }

    private static boolean isDigit(char value) {
        return value >= '0' && value <= '9';
    }

    private void flushPending() {
        for (int index = 0; index < pending.length(); index++) {
            receiver.accept(pending.charAt(index));
        }
        pending.setLength(0);
    }
}
