package io.sagittarius.panamakvm.kvm;

/**
 * Linux KVM UAPI constants for x86-64. Ioctl values are generated by Linux
 * {@code _IO*} macros with type {@code 0xAE}; tests document and verify the
 * encoding instead of treating the decimal values as unexplained literals.
 */
final class KvmUapi {
    /** Stable userspace KVM API version returned by {@code KVM_GET_API_VERSION}. */
    static final int API_VERSION = 12;

    /** System ioctl {@code _IO(0xAE, 0x00)}. */
    static final long GET_API_VERSION = 0x0000_AE00L;
    /** System ioctl {@code _IO(0xAE, 0x01)}. */
    static final long CREATE_VM = 0x0000_AE01L;
    /** System ioctl {@code _IO(0xAE, 0x03)}. */
    static final long CHECK_EXTENSION = 0x0000_AE03L;
    /** System ioctl {@code _IO(0xAE, 0x04)}. */
    static final long GET_VCPU_MMAP_SIZE = 0x0000_AE04L;
    /** System ioctl {@code _IOWR(0xAE, 0x05, struct kvm_cpuid2)}. */
    static final long GET_SUPPORTED_CPUID = 0xC008_AE05L;

    /** VM ioctl {@code _IO(0xAE, 0x41)}. */
    static final long CREATE_VCPU = 0x0000_AE41L;
    /** VM ioctl {@code _IOW(0xAE, 0x46, struct kvm_userspace_memory_region)}. */
    static final long SET_USER_MEMORY_REGION = 0x4020_AE46L;
    /** VM ioctl {@code _IO(0xAE, 0x47)}; scalar argument is the TSS address. */
    static final long SET_TSS_ADDRESS = 0x0000_AE47L;
    /** VM ioctl {@code _IOW(0xAE, 0x48, __u64)}. */
    static final long SET_IDENTITY_MAP_ADDRESS = 0x4008_AE48L;
    /** VM ioctl {@code _IO(0xAE, 0x60)}. */
    static final long CREATE_IRQ_CHIP = 0x0000_AE60L;
    /** VM ioctl {@code _IOW(0xAE, 0x61, struct kvm_irq_level)}. */
    static final long IRQ_LINE = 0x4008_AE61L;
    /** VM ioctl {@code _IOW(0xAE, 0x77, struct kvm_pit_config)}. */
    static final long CREATE_PIT2 = 0x4040_AE77L;

    /** vCPU ioctl {@code _IO(0xAE, 0x80)}. */
    static final long RUN = 0x0000_AE80L;
    /** vCPU ioctl {@code _IOR(0xAE, 0x81, struct kvm_regs)}. */
    static final long GET_REGS = 0x8090_AE81L;
    /** vCPU ioctl {@code _IOW(0xAE, 0x82, struct kvm_regs)}. */
    static final long SET_REGS = 0x4090_AE82L;
    /** vCPU ioctl {@code _IOR(0xAE, 0x83, struct kvm_sregs)}. */
    static final long GET_SREGS = 0x8138_AE83L;
    /** vCPU ioctl {@code _IOW(0xAE, 0x84, struct kvm_sregs)}. */
    static final long SET_SREGS = 0x4138_AE84L;
    /** vCPU ioctl {@code _IOW(0xAE, 0x90, struct kvm_cpuid2)}. */
    static final long SET_CPUID2 = 0x4008_AE90L;

    /** Capability number for userspace-backed guest memory. */
    static final long CAPABILITY_USER_MEMORY = 3L;

    /** {@code KVM_EXIT_IO}: port-I/O needs userspace emulation. */
    static final int EXIT_IO = 2;
    /** {@code KVM_EXIT_HLT}: the guest executed {@code HLT}. */
    static final int EXIT_HALT = 5;
    /** {@code KVM_EXIT_MMIO}: memory-mapped I/O needs userspace emulation. */
    static final int EXIT_MMIO = 6;
    /** {@code KVM_EXIT_SHUTDOWN}: triple fault or architecture shutdown. */
    static final int EXIT_SHUTDOWN = 8;
    /** {@code KVM_EXIT_SYSTEM_EVENT}: shutdown/reset/crash event. */
    static final int EXIT_SYSTEM_EVENT = 24;
    /** {@code KVM_EXIT_IO_IN}: the guest reads from a port. */
    static final int EXIT_IO_IN = 0;
    /** {@code KVM_EXIT_IO_OUT}: the guest writes to a port. */
    static final int EXIT_IO_OUT = 1;

    /** {@code KVM_SYSTEM_EVENT_SHUTDOWN}: guest requested shutdown. */
    static final int SYSTEM_EVENT_SHUTDOWN = 1;
    /** {@code KVM_SYSTEM_EVENT_RESET}: guest requested reset. */
    static final int SYSTEM_EVENT_RESET = 2;
    /** {@code KVM_SYSTEM_EVENT_CRASH}: guest reported a crash. */
    static final int SYSTEM_EVENT_CRASH = 3;

    /** First address in KVM's three-page Intel VMX TSS reservation. */
    static final long TSS_ADDRESS = 0xFFFBD000L;
    /** Page used by KVM for real-mode identity mapping on Intel VMX. */
    static final long IDENTITY_MAP_ADDRESS = 0xFFFBC000L;

    /** CR0 protection-enable bit. */
    static final long CR0_PROTECTION_ENABLE = 1L;
    /** Initial architectural RFLAGS reserved bit, which must remain one. */
    static final long INITIAL_RFLAGS = 1L << 1;

    private KvmUapi() { }
}
